### ISSUE TITLE
Feature PR Checklist

### ISSUE THREAD

**Issue by ZY-Ang** [CS2103AUG2017-W11-B2/main#50]
## Things you need to do before merging every new feature PR:
- [ ] Update **helptext** if necessary
- [ ] Update **tests**
- [ ] Update **developer guide** (your feature implementation)
- [ ] Update **user guide command summary** if necessary
- [ ] Update **user guide main function** description
    1. Text preface including [optional] important notes, background information
    2. Before picture (for new functions only)
    3. Instructions (with optional pictures)
    4. After (success & errors), state outcome (e.g. `You should see...`)
- [ ] Update (or check) **seedu.address.MainApp#VERSION** to the week's version (i.e. 1.2.0) or something and set `isEarlyAccess` to `false`.
- [ ] **Get someone to review your PR!!!**
